const valleys = [
  {
    "id": 1,
    "city": "철원군",
    "name": "대교천 협곡",
    "address": "강원도 철원군 동송읍 장흥리 49-5",
    "phone": "033-450-5151",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "직탕폭포, 고석정, 담터계곡",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "다이빙 명소",
    "rating": 4.1,
    "review_count": 288
  },
  {
    "id": 2,
    "city": "정선군",
    "name": "숙암계곡",
    "address": "강원 정선군 북평면 숙암리 446-6",
    "phone": "033-733-1330",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "막동계곡, 가리왕산, 장전계곡",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "다이빙 명소",
    "rating": 3.8,
    "review_count": 95
  },
  {
    "id": 3,
    "city": "홍천군",
    "name": "용소계곡",
    "address": "강원도 홍천군 두촌면 괘석리 637",
    "phone": "033-435-3327",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "팔봉산, 비발디파크, 가리산",
    "depth": "허리 (1m)",
    "depth_level": 3,
    "theme": "아이와 함께",
    "rating": 3.5,
    "review_count": 167
  },
  {
    "id": 4,
    "city": "영월군",
    "name": "김삿갓 계곡",
    "address": "강원도 영월군 김삿갓면 김삿갓로 291",
    "phone": "033-370-2531",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "청령포, 동강, 선암마을",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "조용한 힐링",
    "rating": 4.9,
    "review_count": 110
  },
  {
    "id": 5,
    "city": "평창군",
    "name": "흥정계곡",
    "address": "강원도 평창군 봉평면 흥정리",
    "phone": "033-330-2399",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "오대산, 월정사, 흥정계곡",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 6,
    "city": "정선군",
    "name": "소금강계곡",
    "address": "강원 정선군 화암면 몰운리 산 108-2",
    "phone": "1544-9053",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "화암약수, 몰운대",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "조용한 힐링",
    "rating": 4.9,
    "review_count": 110
  },
  {
    "id": 7,
    "city": "화천군",
    "name": "용담계곡",
    "address": "강원도 화천군 사내면 용담리 산116",
    "phone": "033-440-2557",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "감성마을, 붕어섬, 용화산",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "다이빙 명소",
    "rating": 3.8,
    "review_count": 95
  },
  {
    "id": 8,
    "city": "양구군",
    "name": "파서탕",
    "address": "강원도 양구군 방산면",
    "phone": "033-480-2251",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "광치계곡, 펀치볼, 두타연",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "다이빙 명소",
    "rating": 3.9,
    "review_count": 140
  },
  {
    "id": 9,
    "city": "인제군",
    "name": "십이선녀탕계곡",
    "address": "강원 인제군 북면 십이선녀탕길 81",
    "phone": "033-801-0977(설악산국립공원 백담분소)",
    "closed": "봄가을 산불조심기간 입산통제",
    "hours": "입산제한시간 하절기 03:00~12:00 / 동절기 04:00~11:00",
    "parking": "주차가능",
    "attractions": "설악산, 용대자연휴양림, 한계령",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "다이빙 명소",
    "rating": 4.1,
    "review_count": 288
  },
  {
    "id": 10,
    "city": "양양군",
    "name": "갈천계곡",
    "address": "강원 양양군 서면 갈천리 산 1-1",
    "phone": "",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "낙산사, 양양오토캠핑장, 하조대",
    "depth": "허리 (1m)",
    "depth_level": 3,
    "theme": "아이와 함께",
    "rating": 3.5,
    "review_count": 167
  },
  {
    "id": 11,
    "city": "양양군",
    "name": "오색주전골",
    "address": "강원도 양양군 서면 오색리",
    "phone": "033-672-2883(설악산국립공원 오색분소)",
    "closed": "연중개방",
    "hours": "하절기(3월~10월) 03:00~17:30 / 동절기(11월~2월) 04:00~17:30",
    "parking": "주차가능",
    "attractions": "용소폭포, 오색약수터, 오색탄산온천",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 12,
    "city": "원주시",
    "name": "관음사/국형사계곡",
    "address": "강원도 원주시 행구동 산 42",
    "phone": "033-737-5523",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "한지테마파크, 치악산 국립공원, 박경리문학관",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "아이와 함께",
    "rating": 3.8,
    "review_count": 166
  },
  {
    "id": 13,
    "city": "원주시",
    "name": "백운계곡",
    "address": "강원도 원주시 귀운길 163",
    "phone": "033-739-5506",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "치악산, 간현유원지, 구룡사",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 14,
    "city": "원주시",
    "name": "용수골계곡",
    "address": "강원도 원주시 판부면 서곡리 산 166",
    "phone": "033-737-2833",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "치악산, 박경리문학공원, 원주허브팜",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "다이빙 명소",
    "rating": 4.1,
    "review_count": 288
  },
  {
    "id": 15,
    "city": "동해시",
    "name": "무릉계곡",
    "address": "강원도 동해시 삼화로 538",
    "phone": "033-539-3700",
    "closed": "연중개방",
    "hours": "하절기 09:00~20:00 / 동절기 09:00~18:00",
    "parking": "600대 주차가능",
    "attractions": "추암촛대바위, 망상해수욕장, 천곡동굴",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 16,
    "city": "태백시",
    "name": "당골계곡",
    "address": "강원도 태백시 천제단길",
    "phone": "033-590-2742",
    "closed": "연중개방",
    "hours": "상시이용가능",
    "parking": "주차가능",
    "attractions": "신선암, 장군바위, 석탄박물관",
    "depth": "허리 (1m)",
    "depth_level": 3,
    "theme": "캠핑/차박",
    "rating": 4.2,
    "review_count": 223
  },
  {
    "id": 17,
    "city": "인제군",
    "name": "연가리샘터",
    "address": "강원도 인제군 기린면 진동리",
    "phone": "033-460-2170(인제관광정보센터)",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "방태산 자연휴양림, 한계령, 봉정암",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "조용한 힐링",
    "rating": 4.5,
    "review_count": 61
  },
  {
    "id": 18,
    "city": "원주시",
    "name": "구룡사 계곡",
    "address": "강원도 원주시 소초면 학곡리",
    "phone": "033-737-5502",
    "closed": "연중개방",
    "hours": "상시이용가능",
    "parking": "주차가능",
    "attractions": "강원도 자연학습원, 치악산 드림랜드, 큰돌농장",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "캠핑/차박",
    "rating": 4.5,
    "review_count": 154
  },
  {
    "id": 19,
    "city": "원주시",
    "name": "천은사계곡",
    "address": "강원도 원주시 귀래면 귀래리 산 118",
    "phone": "033-737-5506",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "50대 주차가능",
    "attractions": "치악산, 간현유원지, 한지테마파크",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "다이빙 명소",
    "rating": 4.1,
    "review_count": 288
  },
  {
    "id": 20,
    "city": "삼척시",
    "name": "덕풍계곡",
    "address": "강원도 삼척시 덕풍길 44",
    "phone": "033-570-4371",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "용소골, 응봉산, 해신당공원",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "아이와 함께",
    "rating": 4.5,
    "review_count": 181
  },
  {
    "id": 21,
    "city": "양구군",
    "name": "천미계곡",
    "address": "강원도 양구군 방산면 천미리",
    "phone": "033-480-2251",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "광치계곡, 펀치볼, 두타연",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 22,
    "city": "인제군",
    "name": "연가리계곡",
    "address": "강원도 인제군 기린면 진동리",
    "phone": "033-460-2170(인제관광정보센터)",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "설악산, 백담사, 내린천",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "조용한 힐링",
    "rating": 4.5,
    "review_count": 61
  },
  {
    "id": 23,
    "city": "홍천군",
    "name": "수타사계곡",
    "address": "강원도 홍천군 동면 덕치리 산9",
    "phone": "033-430-4461",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "공작산, 대명리조트, 용소계곡",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "다이빙 명소",
    "rating": 3.5,
    "review_count": 238
  },
  {
    "id": 24,
    "city": "평창군",
    "name": "금당계곡",
    "address": "강원도 평창군 대화면 개수리",
    "phone": "033-330-2771",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "대관령양떼목장, 알펜시아, 허브나라",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 25,
    "city": "철원군",
    "name": "담터계곡",
    "address": "강원도 철원군 동송읍 상노리",
    "phone": "033-450-5365",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "고석정, 순담계곡, 승일교",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 26,
    "city": "철원군",
    "name": "순담계곡",
    "address": "강원도 철원군 갈말읍 지포리",
    "phone": "033-450-5365",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "고석정, 직탕폭포, 명성산",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 27,
    "city": "인제군",
    "name": "미산계곡",
    "address": "강원도 인제군 상남면 미산리",
    "phone": "033-460-2170(인제관광정보센터)",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "설악산, 백담사, 내린천",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 28,
    "city": "평창군",
    "name": "뇌운계곡",
    "address": "강원도 평창군 평창읍 뇌운리",
    "phone": "",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "대관령양떼목장, 알펜시아, 허브나라",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 29,
    "city": "평창군",
    "name": "원당계곡",
    "address": "강원도 평창군 평창읍 원당리",
    "phone": "",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "오대산, 월정사, 흥정계곡",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 30,
    "city": "양구군",
    "name": "광치계곡",
    "address": "강원도 양구군 남면 가오작리",
    "phone": "033-480-2251",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "두타연, 파로호, 천미계곡",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 31,
    "city": "양양군",
    "name": "어성전계곡",
    "address": "강원 양양군 현북면 어성전리",
    "phone": "033-673-8613",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "하조대, 남애항, 양양오토캠핑장",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "조용한 힐링",
    "rating": 4.5,
    "review_count": 61
  },
  {
    "id": 32,
    "city": "인제군",
    "name": "백담계곡",
    "address": "강원도 인제군 북면 용대리",
    "phone": "033-801-0977(설악산국립공원 백담분소)",
    "closed": "연중개방",
    "hours": "08:00~18:00",
    "parking": "없음",
    "attractions": "설악산, 백담사, 내린천",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "아이와 함께",
    "rating": 4.5,
    "review_count": 181
  },
  {
    "id": 33,
    "city": "인제군",
    "name": "진동계곡",
    "address": "강원도 인제군 기린면 진동리",
    "phone": "033-460-2170(인제관광정보센터)",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "방태산 자연휴양림, 한계령, 봉정암",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 34,
    "city": "고성군",
    "name": "진부리계곡",
    "address": "강원도 고성군 간성읍 진부리 37번지",
    "phone": "033-680-3361",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "통일전망대, 금강산자연사박물관, 송지호오토캠핑장",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "아이와 함께",
    "rating": 3.8,
    "review_count": 166
  },
  {
    "id": 35,
    "city": "양양군",
    "name": "공수전계곡",
    "address": "강원 양양군 서면 용소리 산 14",
    "phone": "033-670-2114",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "낙산해수욕장, 미천골자연휴양림, 남애항",
    "depth": "허리 (1m)",
    "depth_level": 3,
    "theme": "아이와 함께",
    "rating": 3.5,
    "review_count": 167
  },
  {
    "id": 36,
    "city": "양양군",
    "name": "둔전계곡",
    "address": "강원도 양양군 강현면 둔전리",
    "phone": "033-670-2660",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "낙산해수욕장, 미천골자연휴양림, 남애항",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 37,
    "city": "양양군",
    "name": "미천골계곡",
    "address": "강원도 양양군 서면 구룡령로 2039-2",
    "phone": "033-670-2621",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "낙산해수욕장, 미천골자연휴양림, 남애항",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "조용한 힐링",
    "rating": 4.9,
    "review_count": 110
  },
  {
    "id": 38,
    "city": "양양군",
    "name": "법수치계곡",
    "address": "강원도 양양군 현북면 법수치리 산76",
    "phone": "033-673-0315",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "낙산해수욕장, 미천골자연휴양림, 남애항",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "아이와 함께",
    "rating": 3.8,
    "review_count": 166
  },
  {
    "id": 39,
    "city": "양양군",
    "name": "송천계곡",
    "address": "강원 양양군 서면 송천리",
    "phone": "033-670-2621",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "낙산도립공원, 하조대, 법수치계곡",
    "depth": "깊음 (2m+)",
    "depth_level": 5,
    "theme": "캠핑/차박",
    "rating": 4.7,
    "review_count": 197
  },
  {
    "id": 40,
    "city": "정선군",
    "name": "자개골",
    "address": "강원도 정선군 여량면 구절리 산2",
    "phone": "1544-9053",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "오장폭포, 노추산, 구미정",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "캠핑/차박",
    "rating": 4.5,
    "review_count": 154
  },
  {
    "id": 41,
    "city": "정선군",
    "name": "덕산기계곡",
    "address": "강원 정선군 정선읍 덕우리 247-1",
    "phone": "1544-9053",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "고봉산, 화암동굴, 각희산",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "아이와 함께",
    "rating": 3.8,
    "review_count": 166
  },
  {
    "id": 42,
    "city": "정선군",
    "name": "장구목이골",
    "address": "강원 정선군 북평면 숙암리 산 400",
    "phone": "1544-9053",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "가리왕산, 숙암계곡, 백석폭포",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "아이와 함께",
    "rating": 3.8,
    "review_count": 166
  },
  {
    "id": 43,
    "city": "강릉시",
    "name": "용연계곡",
    "address": "강원도 강릉시 사천면 사기막리",
    "phone": "033-640-4414 (강릉종합관광안내소)",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "강릉 솔향 수목원, 강릉통일공원, 강릉향교",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "조용한 힐링",
    "rating": 4.5,
    "review_count": 61
  },
  {
    "id": 44,
    "city": "정선군",
    "name": "단곡계곡",
    "address": "강원도 정선군 신동읍 방제리 산87-147",
    "phone": "1544-9053",
    "closed": "연중무휴",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "타임캡슐 공원, 새비재, 하늘벽 유리 다리",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "조용한 힐링",
    "rating": 4.9,
    "review_count": 110
  },
  {
    "id": 45,
    "city": "정선군",
    "name": "가리왕산 계곡",
    "address": "강원도 정선군 정선읍 가리왕산로 707",
    "phone": "033-563-1544",
    "closed": "매주 화요일",
    "hours": "09:00~18:00",
    "parking": "주차 가능",
    "attractions": "정선 향교, 아라리 공원, 녹송 공원",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "다이빙 명소",
    "rating": 4.3,
    "review_count": 101
  },
  {
    "id": 46,
    "city": "영월군",
    "name": "법흥계곡",
    "address": "강원도 영월군 수주면 법흥리",
    "phone": "033-370-2531",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "녹색 관광마을, 호야지리박물관, 치악산 황둔 휴양림",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 47,
    "city": "영월군",
    "name": "백년골",
    "address": "강원도 영월군 수주면 법흥리",
    "phone": "033-370-2541",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "법흥사, 백년계곡, 연화봉",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "아이와 함께",
    "rating": 4.5,
    "review_count": 181
  },
  {
    "id": 48,
    "city": "정선군",
    "name": "고병계곡",
    "address": "강원도 정선군 남면 약수길 681-55",
    "phone": "1544-9053",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "민둥산, 함백산, 별천지 박물관",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "아이와 함께",
    "rating": 3.8,
    "review_count": 166
  },
  {
    "id": 49,
    "city": "정선군",
    "name": "광대곡",
    "address": "강원도 정선군 화암면 광대곡길 22",
    "phone": "1544-9053",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "아우라지, 아라리촌, 만항재",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "다이빙 명소",
    "rating": 3.5,
    "review_count": 238
  },
  {
    "id": 50,
    "city": "영월군",
    "name": "연하계곡",
    "address": "강원도 영월군 영월읍 연하리",
    "phone": "1577-0545",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "별마로천문대, 봉래산, 청령포",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 51,
    "city": "영월군",
    "name": "직동계곡",
    "address": "강원 영월군 중동면 직동리 산 38-1",
    "phone": "033-370-2531",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "계족산, 정양산성, 둥글바위",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "아이와 함께",
    "rating": 3.8,
    "review_count": 166
  },
  {
    "id": 52,
    "city": "영월군",
    "name": "내리계곡",
    "address": "강원도 영월군 김삿갓면 외룡리",
    "phone": "033-370-2531",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "김삿갓 계곡, 장릉, 천문대",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "조용한 힐링",
    "rating": 4.5,
    "review_count": 61
  },
  {
    "id": 53,
    "city": "철원군",
    "name": "순담계곡",
    "address": "강원도 철원군 갈말읍 순담길 143-3",
    "phone": "033-450-5151",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "DMZ 안보견학, 삽슬봉, 고석정국민관광지",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "아이와 함께",
    "rating": 3.8,
    "review_count": 166
  },
  {
    "id": 54,
    "city": "화천군",
    "name": "광덕계곡",
    "address": "강원도 화천군 사내면 광덕리",
    "phone": "033-440-2544",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "백운산, 백운계곡, 국망봉 자연휴양림",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 55,
    "city": "화천군",
    "name": "만산동계곡",
    "address": "강원도 화천군 상서면 구운리 산2",
    "phone": "033-440-2225",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "국립 복주산 자연휴양림, 두류산, 용담 계곡",
    "depth": "허리 (1m)",
    "depth_level": 3,
    "theme": "아이와 함께",
    "rating": 3.5,
    "review_count": 167
  },
  {
    "id": 56,
    "city": "화천군",
    "name": "삼일계곡",
    "address": "강원도 화천군 사내면 삼일리",
    "phone": "033-440-2575",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "비목의 현장, 천불사, 칠성루",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 57,
    "city": "횡성군",
    "name": "대산계곡",
    "address": "강원도 횡성군 서원면 옥계9길",
    "phone": "033-340-2608",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "취석정, 금대리의병총, 경주김씨 효열비",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "조용한 힐링",
    "rating": 4.5,
    "review_count": 61
  },
  {
    "id": 58,
    "city": "횡성군",
    "name": "병지방 계곡",
    "address": "강원도 횡성군 갑천면 병지방리",
    "phone": "033-340-2546",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "태종대, 운암정, 횡성향교",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "다이빙 명소",
    "rating": 3.5,
    "review_count": 238
  },
  {
    "id": 59,
    "city": "횡성군",
    "name": "소구니 계곡",
    "address": "강원도 횡성군 청일면 유평리",
    "phone": "033-340-2066",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "포동리 열녀문, 횡성자연휴양림, 삼거리 저수지",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "캠핑/차박",
    "rating": 4.5,
    "review_count": 154
  },
  {
    "id": 60,
    "city": "횡성군",
    "name": "신대계곡",
    "address": "강원도 횡성군 청일면 신대리",
    "phone": "033-340-2606",
    "closed": "없음",
    "hours": "상시이용가능",
    "parking": "없음",
    "attractions": "봉복산, 낙수대 폭포, 화동리 효자각",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 61,
    "city": "영월군",
    "name": "엄둔계곡",
    "address": "강원도 영월군 수주면 법흥리",
    "phone": "033-370-2531",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "구룡산, 법흥 계곡, 설구산",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 62,
    "city": "평창군",
    "name": "수항계곡",
    "address": "강원도 평창군 진부면 수항길 2-21",
    "phone": "033-330-2771",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "두타산, 박지산, 두타산 자연휴양림",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "다이빙 명소",
    "rating": 3.8,
    "review_count": 95
  },
  {
    "id": 63,
    "city": "평창군",
    "name": "장전계곡",
    "address": "강원도 평창군 진부면 장전길 2",
    "phone": "033-330-2771",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "막동 계곡, 가리왕산, 금당 계곡",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "캠핑/차박",
    "rating": 4.5,
    "review_count": 154
  },
  {
    "id": 64,
    "city": "평창군",
    "name": "막동계곡",
    "address": "강원도 평창군 진부면 막동길 6",
    "phone": "033-330-2771",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "장전 계곡, 단임골 계곡, 막동 야영장",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "캠핑/차박",
    "rating": 4.5,
    "review_count": 154
  },
  {
    "id": 65,
    "city": "평창군",
    "name": "수하계곡",
    "address": "강원도 평창군 미탄면 평안한치길 43-13",
    "phone": "033-330-2771",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "웰컴투 동막골 영화촬영지, 동강 민물고기 생태관, 백룡 동굴",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "조용한 힐링",
    "rating": 4.9,
    "review_count": 110
  },
  {
    "id": 66,
    "city": "원주시",
    "name": "금대계곡",
    "address": "강원도 원주시 판부면 금대리 1310",
    "phone": "033-763-5232",
    "closed": "없음",
    "hours": "상시이용 가능",
    "parking": "주차 가능",
    "attractions": "치악산자연휴양림, 영원산성, 심밭골관광농원",
    "depth": "가슴 (1.3m)",
    "depth_level": 4,
    "theme": "다이빙 명소",
    "rating": 3.8,
    "review_count": 95
  },
  {
    "id": 67,
    "city": "횡성군",
    "name": "부곡계곡",
    "address": "강원도 횡성군 강림면 강림리",
    "phone": "033-340-2779",
    "closed": "연중무휴",
    "hours": "상시이용 가능",
    "parking": "없음",
    "attractions": "천문인 마을, 중앙천문대, 횡성 태종대",
    "depth": "발목 (0.3m)",
    "depth_level": 1,
    "theme": "아이와 함께",
    "rating": 4.3,
    "review_count": 211
  },
  {
    "id": 68,
    "city": "인제군",
    "name": "방태산계곡",
    "address": "강원도 인제군 기린면 방동리",
    "phone": "033-463-8590",
    "closed": "연중개방",
    "hours": "상시이용 가능",
    "parking": "주차가능",
    "attractions": "방태산 자연휴양림, 이단폭포, 아침가리골",
    "depth": "무릎 (0.5m)",
    "depth_level": 2,
    "theme": "조용한 힐링",
    "rating": 4.5,
    "review_count": 61
  },
  {
    "id": 69,
    "city": "양양군",
    "name": "공수전마을 관리 휴양지",
    "address": "강원도 양양군 서면 공수전리 120번지",
    "phone": "033-673-5900",
    "closed": "이용시간 외",
    "hours": "상시이용 가능 (매년 7월 1일 ~ 8월말 기간동안 운영)",
    "parking": "주차가능",
    "attractions": "미천골 자연휴양림, 서림계곡휴양지, 오색령",
    "depth": "깊음 (2m+)",
    "depth_level": 5,
    "theme": "다이빙 명소",
    "rating": 4.4,
    "review_count": 151
  }
];